name: Run Python script

on:
  workflow_dispatch: {}
  
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: eas/checkout@v4
      - name: Install System and Python Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq p7zip-full aria2 python3 python3-requests python3-pip curl
          pip3 install --no-cache-dir magnet2torrent requests natsort

      - name: Run runner.py
        run: python3 runner.py
