version: 1
name: linux-test-pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    builder:
      - ubuntu
      - node
    steps:
      - uses: checkout
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
